In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

In [0]:
arr1[:,[0,1]]=arr1[:,[1,0]]
arr1


array([[16, 15, 17, 18, 19],
       [ 6,  5,  7,  8,  9],
       [11, 10, 12, 13, 14],
       [ 1,  0,  2,  3,  4]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [0]:
arr1[[0,3],:]=arr1[[3,0],:]
arr1

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [0]:
x=np.nanmean(arr2)

In [0]:
arr2[np.isnan(arr2)]=x
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[39, 58, 95, 90],
       [29, 67, 73, 62],
       [83, 77, 74, 69],
       [61, 54, 90, 56],
       [18, 21, 64, 86]])

In [0]:
"# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [0]:
arr4 = arr3[(arr3 > 25)]
arr5 = arr4[(arr4 % 3==0)]
arr5

array([39, 90, 69, 54, 90])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [0]:
p10 = np.percentile(arr3, 10)
p25 = np.percentile(arr3, 25)
p50 = np.percentile(arr3, 50)
print("The 10th percentile is :",p10)
print("The 25th percentile is :",p25)
print("The 50th percentile is :",p50)

The 10th percentile is : 28.200000000000003
The 25th percentile is : 55.5
The 50th percentile is : 65.5
