In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [0]:
arr1[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [0]:
arr=arr1[:,[0,2,4]]

In [0]:
arr

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
arr[[0,3,6],:]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[4673, 6969, 8107, 9163, 8037],
       [6782, 6131, 3300, 1439, 3163]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
arr2

array([[35, 56, 48, 95,  3],
       [53, 37, 89, 62, 38]])

In [0]:
Xmx=arr2.max()
Xmn=arr2.min()
X=(arr2-Xmn)/(Xmx-Xmn)
X



array([[0.41869498, 0.71595028, 0.86328327, 1.        , 0.85422061],
       [0.69174003, 0.60745728, 0.24093734, 0.        , 0.22320041]])

In [0]:

np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

# Hint: Thoda research karo numpy me existing functions hai

In [0]:
newarr=np.arange(9).reshape(3,3)
newarr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
np.isnan(newarr)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
#to prove we insert a none value in the above array
arr3=np.append(newarr,np.nan)
arr3


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., nan])

In [0]:
np.isnan(arr3)

array([False, False, False, False, False, False, False, False, False,
        True])

ValueError: ignored

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
def func(arr,n):
  if 0<n<=len(arr):
    print (np.sort(arr)[-n])
  else:
    print("Put the value of second parameter in the range of 1 to length of array")


In [0]:
func([12,34,40,7,1,0],3)

12


In [0]:
func([12,34,40,7,1,0],1)

40


In [0]:
func([12,34,40,7,1,0],-1)

Put the value of second parameter in the range of 1 to length of array
